### ISSUE TITLE
The extension no longer shares links

### ISSUE THREAD

**Issue by scrutinizer11** [asamuzaK/shareSNS#24] opened 2021-07-07 01:59 UTC
The extension doesn't share links, but only comments in a private message.

Open any web page, summon the sharing dialog by clicking on Share With SNS. Choose "Share in a private message", then choose a contact, jot down a couple of lines, hit "Send". Only this text is shared but not the page.

BTW, every time I click "Share with SNS" "Share Link" is greyed out.

**Comment by asamuzaK** [comment] 2021-07-07 11:12
You're probably talking about Facebook, but in the first place, the extension doesn't have a "Share in a private message" menu item, so I'm confused.
Please explain in more detail with screenshots etc.

**Comment by scrutinizer11** [comment] 2021-07-08 02:41
Share as a link greyed out 
![Share as a link greyed out](https://user-images.githubusercontent.com/45983734/124853559-bb9f1280-dfae-11eb-8302-99ecc8c2b664.png)

Sharer - the page is not shared, only the optional message is
![Sharer - this link is not shared, only the message is](https://user-images.githubusercontent.com/45983734/124853589-cb1e5b80-dfae-11eb-916d-d864c5231810.png)

**Comment by asamuzaK** [comment] 2021-07-09 00:34
> Share as a link greyed out

Share Link menu is enabled when you select a link within the page.
![share_link](https://user-images.githubusercontent.com/6790339/125005634-2fb4e580-e097-11eb-907e-114ce9e6c213.png)

> Sharer - the page is not shared, only the optional message is

The page shown is created by Facebook API, not by this extension.
This extension only opens a new page with the URL `https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Froutinehub.co%2Fshortcut%2F8089%2F`.
So it's not a bug in this extension.

**Comment by asamuzaK** [comment] 2021-07-12 10:54
I'll close this.
If you have any opinions, please reopen.

**Closed as completed by asamuzaK** 2021-07-12 10:54 UTC
